default:
    image: node:latest
    interruptible: true
    tags:
        - shared-small

stages:
    - install
    - lint
    - security
    - build
    - test
    - publish

variables:
    NPM_CONFIG_REGISTRY: 'https://nexus.protontech.ch/repository/web-npm/'

workflow:
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        - if: $CI_COMMIT_TAG
        - when: never

include:
    - component: 'gitlab.protontech.ch/proton/devops/cicd-components/kits/devsecops/semgrep@0.0.39'
      inputs:
          runner-tag: shared-small
          stage: security
      rules:
          - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
          - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          - if: $CI_COMMIT_TAG
          - if: $CI_PIPELINE_SOURCE == "schedule"
            when: never

.pnpm_setup: &pnpm_setup
    before_script:
        - npm install -g pnpm

install:
    <<: *pnpm_setup
    stage: install
    script:
        - pnpm install --frozen-lockfile
    artifacts:
        expire_in: 1 hours
        paths:
            - node_modules
            - pnpm-lock.yaml

lint:
    <<: *pnpm_setup
    stage: lint
    script:
        - pnpm run lint
    dependencies:
        - install

build:
    <<: *pnpm_setup
    stage: build
    script:
        - pnpm install --frozen-lockfile
        - pnpm run build
    artifacts:
        paths:
            - dist
    dependencies:
        - install

test:
    <<: *pnpm_setup
    stage: test
    script:
        - pnpm test
    dependencies:
        - install
        - build

publish:
    <<: *pnpm_setup
    stage: publish
    only:
        - /^v\d+\.\d+\.\d+$/
    script:
        # Configure npm for Nexus with the correct auth token format
        - echo "//nexus.protontech.ch/repository/web-npm/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
        - echo "registry=https://nexus.protontech.ch/repository/web-npm/" >> .npmrc
        - echo "@proton:registry=https://nexus.protontech.ch/repository/web-npm/" >> .npmrc
        - pnpm publish --no-git-checks
    dependencies:
        - build
        - test
